/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marshal_opencvproto_Detector */

#ifndef _Included_marshal_opencvproto_Detector
#define _Included_marshal_opencvproto_Detector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     marshal_opencvproto_Detector
 * Method:    detect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_marshal_opencvproto_Detector_detect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     marshal_opencvproto_Detector
 * Method:    generateHistogram
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_marshal_opencvproto_Detector_generateHistogram
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
